core/src/main/scala/com/spotify/featran/FeatureSpec.scala
core/src/test/scala/com/spotify/featran/FeatureSpecSpec.scala

At times features will need to be extracted with more fields in the case of labels etc.  This review makes it so you can reuse those aggregations generated previously where the new features to be extracted is a subset of the original features.  If the new features is not a strict subset an error is thrown.

Map features into previously stored settings

---

core/src/main/scala/com/spotify/featran/FeatureExtractor.scala
scio/src/test/scala/com/spotify/featran/scio/ScioTest.scala

If fs is not serializable it would be null out by CC, which would
result in NPE, instead make sure that fs is not null out, and fail
earlier and with serialization exception.

Make non serializable error explicit instead of "silent" NPE

---

core/src/main/scala/com/spotify/featran/transformers/NHotWeightedEncoder.scala
core/src/main/scala/com/spotify/featran/transformers/VectorIdentity.scala
core/src/test/scala/com/spotify/featran/examples/Example.scala
core/src/test/scala/com/spotify/featran/transformers/NHotWeightedEncoderSpec.scala
core/src/test/scala/com/spotify/featran/transformers/VectorIdentitySpec.scala

The Vector Identity Transformer makes it easy to take a dense vector and push it through into the features.  NHotWeightedEncoder is similar to NHotEncoder but where each field has a weight.  For example when you have some probability that a label belongs on an item.

VectorIdentity and NHotWeightedEncoder Transformers

---

core/src/main/scala/com/spotify/featran/transformers/VonMisesEvaluator.scala
core/src/test/scala/com/spotify/featran/examples/Example.scala
core/src/test/scala/com/spotify/featran/transformers/VonMisesEvaluatorSpec.scala

This PR adds a von Mises distribution evaluator as a new transformer. The use case is for converting the time of day to a feature vector that captures the circularity of time.

add von mises transformer

---

core/src/main/scala/com/spotify/featran/FeatureBuilder.scala

Addresses part of the problem detailed in:
https://github.com/spotify/featran/issues/20
It is impractical to iteratively call skip n times for large n.
@richwhitjr @nevillelyh

overwrite skip n function

---

core/src/main/scala/com/spotify/featran/transformers/OneHotEncoder.scala

Rewrite of one hot encoding that uses a hash map instead of a list. Needed for when the number of tokens is large. Addresses the issue detailed in:
https://github.com/spotify/featran/issues/20
@richwhitjr @nevillelyh

use hash map instead of list for one hot encoder

---

core/src/main/scala/com/spotify/featran/transformers/HashNHotEncoder.scala
core/src/main/scala/com/spotify/featran/transformers/HashNHotWeightedEncoder.scala
core/src/main/scala/com/spotify/featran/transformers/HashOneHotEncoder.scala

Fix for #31 
Calls to fb.init() in Hash*HotEncoder causes the length of SparseVector to be set incorrectly since fb.init() should be called once per record.

fb.init() should be called once per record

---

core/src/main/scala/com/spotify/featran/transformers/NGrams.scala
core/src/test/scala/com/spotify/featran/Fixtures.scala
core/src/test/scala/com/spotify/featran/transformers/NGramsSpec.scala

@nevillelyh PTAL. Gonna leave some comments / questions in a few places.

Add NGramsTransformer, fix #52

---

java/src/main/scala/com/spotify/featran/java/JavaOps.scala
java/src/test/scala/com/spotify/featran/java/JavaTest.scala

Memoizing sparse array feature builder fail in concurrent environment
because that builder holds state.

Fix concurrency problem in java and sparse arrays

---

build.sbt
core/src/main/scala/com/spotify/featran/FeatureBuilder.scala
jmh/src/test/scala/com/spotify/featran/jmh/FeatureBuilderBenchmark.scala
tensorflow/src/main/scala/com/spotify/featran/tensorflow/package.scala

```
[info] # Run complete. Total time: 00:02:22
[info] Benchmark                             Mode  Cnt      Score      Error  Units
[info] FeatureBuilderBenchmark.array         avgt   10   9597.619 ± 2103.568  ns/op
[info] FeatureBuilderBenchmark.denseVector   avgt   10   9064.211 ±   77.171  ns/op
[info] FeatureBuilderBenchmark.map           avgt   10  66832.117 ± 2732.898  ns/op
[info] FeatureBuilderBenchmark.seq           avgt   10  13010.496 ±  664.425  ns/op
[info] FeatureBuilderBenchmark.sparseArray   avgt   10   8938.740 ±   96.700  ns/op
[info] FeatureBuilderBenchmark.sparseVector  avgt   10  66165.036 ± 2033.404  ns/op
[info] FeatureBuilderBenchmark.tensorflow    avgt   10  49127.317 ± 2873.874  ns/op
```

add FeatureBuilder benchmarks

---

core/src/main/scala/com/spotify/featran/FeatureSpec.scala
core/src/test/scala/com/spotify/featran/FeatureSpecSpec.scala

This method should hopefully make it easier to share feature specs when you have a spec that depends on some sub type of a larger object.  The idea is that you have some custom class that is specific to your domain you may have sub object that you share across projects.
The function in the method allows for the mapping between the higher level object and the reusable spec object.

Feature Spec Extension

---

core/src/main/scala/com/spotify/featran/FeatureBuilder.scala
core/src/main/scala/com/spotify/featran/transformers/PositionEncoder.scala
core/src/test/scala/com/spotify/featran/Fixtures.scala
core/src/test/scala/com/spotify/featran/transformers/PositionEncoderSpec.scala
examples/src/main/scala/Examples.scala

Fixes #91.  General idea is that instead of outputting a binary vector the transformer instead outputs the position of the category in the sorted sets of possible values. The one small quirk of this though is that missing data will collide with the 0 position.  For labels the first class having a position of 0 seems standard so I don't think we want 1 index.
To work around collisions there is now a new rejection type called Collide that users can remove if they know they don't expect missing values in the category.
The thought is that this transformer would mostly be used around labels for supervised problems so removing rows with missing labels may be reasonable.

PositionEncoder Transformer

---

core/src/main/scala/com/spotify/featran/transformers/OneHotEncoder.scala

When `encodeMissingValue` is true the dimension of the features will be the number of entries in the sorted map plus 1 for `__missing__`

increase dim by 1 for encodeMissingValue

---

build.sbt

After a little bit more digging around dependency resolution/conflicts ... I think it's wise to revert this change. The eviction `warn` that we get is only about a transitive dependency. If it was a direct one the story would be different.

Revert #102

---

core/src/main/scala/com/spotify/featran/transformers/NHotEncoder.scala
core/src/main/scala/com/spotify/featran/transformers/NHotWeightedEncoder.scala

Want to treat the case where `xs` is an empty sequence as a missing value. In this case `keys` would also be empty.

treat empty input as a missing value

---

core/src/main/scala/com/spotify/featran/FlatConverter.scala
core/src/main/scala/com/spotify/featran/FlatExtractor.scala
core/src/main/scala/com/spotify/featran/transformers/Binarizer.scala
core/src/main/scala/com/spotify/featran/transformers/Bucketizer.scala
core/src/main/scala/com/spotify/featran/transformers/HashNHotEncoder.scala
core/src/main/scala/com/spotify/featran/transformers/HashNHotWeightedEncoder.scala
core/src/main/scala/com/spotify/featran/transformers/HashOneHotEncoder.scala
core/src/main/scala/com/spotify/featran/transformers/HeavyHitters.scala
core/src/main/scala/com/spotify/featran/transformers/Identity.scala
core/src/main/scala/com/spotify/featran/transformers/MDL.scala
core/src/main/scala/com/spotify/featran/transformers/MaxAbsScaler.scala
core/src/main/scala/com/spotify/featran/transformers/MinMaxScaler.scala
core/src/main/scala/com/spotify/featran/transformers/NHotEncoder.scala
core/src/main/scala/com/spotify/featran/transformers/NHotWeightedEncoder.scala
core/src/main/scala/com/spotify/featran/transformers/Normalizer.scala
core/src/main/scala/com/spotify/featran/transformers/OneHotEncoder.scala
core/src/main/scala/com/spotify/featran/transformers/PolynomialExpansion.scala
core/src/main/scala/com/spotify/featran/transformers/PositionEncoder.scala
core/src/main/scala/com/spotify/featran/transformers/QuantileDiscretizer.scala
core/src/main/scala/com/spotify/featran/transformers/QuantileOutlierRejector.scala
core/src/main/scala/com/spotify/featran/transformers/StandardScaler.scala
core/src/main/scala/com/spotify/featran/transformers/TopNOneHotEncoder.scala
core/src/main/scala/com/spotify/featran/transformers/Transformer.scala
core/src/main/scala/com/spotify/featran/transformers/VectorIdentity.scala
core/src/main/scala/com/spotify/featran/transformers/VonMisesEvaluator.scala
tensorflow/src/main/scala/com/spotify/featran/tensorflow/package.scala
tensorflow/src/test/scala/com/spotify/featran/tensorflow/ExampleConverterSpec.scala

This PR adds a new TypeClass and function that allows a user to use the functions internal to a FeatureSpec to convert to a new flat keyed feature type.  This review adds support for tf.examples but json and tablerows are other examples of possible converters.

Convert function between Scala Objects and a Flat Keyed Type

---

core/src/main/scala/com/spotify/featran/FlatExtractor.scala
core/src/main/scala/com/spotify/featran/MultiFeatureSpec.scala
tensorflow/src/test/scala/com/spotify/featran/tensorflow/ExampleExtractorSpec.scala

Followup to the past few PRs.  These functions allow the conversion from a known FeatureSpec on some type T to a Spec that can read and extract data from the intermediate keyed sources that are now possible to map between.
Example would be earlier using the Spec to convert T to tf.examples and now wanting to generate a settings file from these examples stored somewhere.

Functions to convert Spec to FlatSpec to allow aggregations from keyed sources.

---

core/src/main/scala/com/spotify/featran/FlatExtractor.scala
core/src/main/scala/com/spotify/featran/json/package.scala
core/src/main/scala/com/spotify/featran/transformers/Bucketizer.scala
core/src/main/scala/com/spotify/featran/transformers/VectorIdentity.scala
core/src/main/scala/com/spotify/featran/transformers/VonMisesEvaluator.scala
core/src/test/scala/com/spotify/featran/transformers/BucketizerSpec.scala
core/src/test/scala/com/spotify/featran/transformers/TransformerProp.scala
core/src/test/scala/com/spotify/featran/transformers/VectorIdentitySpec.scala
core/src/test/scala/com/spotify/featran/transformers/VonMisesEvaluatorSpec.scala

This adds a new package to core that allows for reading/writing to a JSON intermediate format.  Also because we have this typeclass implemented in core the converters can be added to transformers to make sure it works everywhere.

Add JSON Reader/Writer to Core

---

build.sbt

@ravwojdyla found a potential issue with the new version. Let's do this in the next release.

Revert TensorFlow to 1.8.0

---

core/src/main/scala/com/spotify/featran/transformers/Transformer.scala
core/src/test/scala/com/spotify/featran/transformers/TransformerProp.scala

Adds a `contramap` method to the `Transformer`, to make it slightly easier to write custom Transformers (which seems to be a pain, right now: #103).
This could already mostly be done in the `require` lambda, but having `contramap` on the `Transformer` makes it easier to reuse custom transformers.
Example usage:
```scala
import com.spotify.featran._
import com.spotify.featran.transformers._
case class Student(name: String, age: Int, height: Double)
case class Course(students: List[Student])
val data = Seq(
Course(
List(
Student("Anna", 20, 1.65),
Student("Brad", 23, 1.72),
Student("Peter", 19, 1.63)
)
),
Course(
List(
Student("Alice", 30, 1.59),
Student("Bob", 32, 1.67),
Student("Chloe", 25, 1.55),
Student("Dennis", 27, 1.80)
)
)
)
// Using base Transformers to create more complex …
```

Add contramap method to Transformer

---

core/src/main/scala/com/spotify/featran/transformers/HashNHotEncoder.scala
core/src/main/scala/com/spotify/featran/transformers/HashNHotWeightedEncoder.scala

This PR enables using empty sequences as input values for `HashNHotEncoder` and `HashNHotWeightedEncoder`.

Allow empty sequences as input values for HashNHotEncoders

---

core/src/test/scala/com/spotify/featran/transformers/TransformerProp.scala

`==` will fail if the results contain `NaN`.

fix contramap test flakiness

---

.scalafmt.conf
build.sbt
core/src/main/scala/com/spotify/featran/CollectionType.scala
core/src/main/scala/com/spotify/featran/CrossingFeatureBuilder.scala
core/src/main/scala/com/spotify/featran/FeatureBuilder.scala
core/src/main/scala/com/spotify/featran/converters/CaseClassConverter.scala
core/src/main/scala/com/spotify/featran/transformers/NHotEncoder.scala
core/src/main/scala/com/spotify/featran/transformers/VectorIdentity.scala
core/src/test/scala/com/spotify/featran/FeatureSpecSpec.scala
numpy/src/main/scala/com/spotify/featran/numpy/NumPy.scala
tensorflow/src/main/scala/com/spotify/featran/tensorflow/package.scala

The dangling implicits are new default:
https://scalameta.org/scalafmt/docs/configuration.html#newlines-around-implicit-parameter-list-modifier

Bump scalafmt to 2.5.1

---

core/src/main/scala/com/spotify/featran/FeatureSpec.scala

`Feature` was escaping scope through `FeatureSpec#filter`

Make Feature constructor private package

---

.scalafmt.conf
project/build.properties

This commit bumps SBT to version 1.5.6.
SBT uses log4j internally for logging. A recent vulnerability has
surfaced which allows for remote code execution. SBT 1.5.6 has
been patched to include fixes for log4j internally.

Upgrade SBT to 1.5.6

---

build.sbt
java/src/main/java/com/spotify/featran/java/SerializableFunction.java
java/src/main/scala/com/spotify/featran/java/JavaOps.scala
java/src/test/scala/com/spotify/featran/java/JavaTest.scala

`java` module wasn't building with scala 3 due to type conflict as explained in https://github.com/lampepfl/dotty/discussions/16797#discussioncomment-4845603.
Proposed solution to change compiling order worked

Add scala3 support for the java module

---

build.sbt

CI is failing on main due to some javadoc warnings on the `java` module.
As we do not publish the javadoc, just filter the `-Xfatal-warnings` compiler option if set for the `doc` task

Ignore javadoc warnings
